on:
  push:
    branches:
      - main
jobs:
  triggerRepo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Checkout Repo B
        uses: actions/checkout@v3
        with:
          repository: chinmayjain08/Jenkins_Apache
          token: ${{ secrets.REPO_B_TOKEN }}
          path: apache-repo
      - name: List files from Repo B
        run: ls -la apache-repo
